apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-egressgateway","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"egressgateway","istio.io/rev":"default","operator.istio.io/component":"EgressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.3","release":"istio"},"name":"istio-egressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"http2","port":80,"targetPort":8080},{"name":"https","port":443,"targetPort":8443}],"selector":{"app":"istio-egressgateway","istio":"egressgateway"},"type":"ClusterIP"}}
    creationTimestamp: "2021-02-17T17:01:26Z"
    labels:
      app: istio-egressgateway
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: egressgateway
      istio.io/rev: default
      operator.istio.io/component: EgressGateways
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.7.3
      release: istio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
            f:istio: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: istioctl
      operation: Update
      time: "2021-02-17T17:01:26Z"
    name: istio-egressgateway
    namespace: istio-system
    resourceVersion: "3421258"
    selfLink: /api/v1/namespaces/istio-system/services/istio-egressgateway
    uid: a6c2f821-35c6-44a0-90b9-2d447d570b1a
  spec:
    clusterIP: 10.100.200.137
    ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: istio-egressgateway
      istio: egressgateway
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"ingressgateway","istio.io/rev":"default","operator.istio.io/component":"IngressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.3","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"status-port","port":15021,"targetPort":15021},{"name":"http2","port":80,"targetPort":8080},{"name":"https","port":443,"targetPort":8443}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
    creationTimestamp: "2021-02-17T17:01:26Z"
    labels:
      app: istio-ingressgateway
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: ingressgateway
      istio.io/rev: default
      operator.istio.io/component: IngressGateways
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.7.3
      release: istio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15021,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
            f:istio: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: istioctl
      operation: Update
      time: "2021-02-17T17:01:26Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: akc
      operation: Update
      time: "2021-02-17T17:01:32Z"
    name: istio-ingressgateway
    namespace: istio-system
    resourceVersion: "3421390"
    selfLink: /api/v1/namespaces/istio-system/services/istio-ingressgateway
    uid: 7de38339-7360-417d-b95e-1b8b978a5df7
  spec:
    clusterIP: 10.100.200.156
    externalTrafficPolicy: Cluster
    ports:
    - name: status-port
      nodePort: 32097
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 31645
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 31938
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: istio-ingressgateway.istio-system.avi.charterlab.local
        ip: 172.16.1.6
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mixer","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"mixer","istio.io/rev":"default","operator.istio.io/component":"Telemetry","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.3","release":"istio"},"name":"istio-telemetry","namespace":"istio-system"},"spec":{"ports":[{"name":"grpc-mixer","port":9091},{"name":"grpc-mixer-mtls","port":15004},{"name":"http-monitoring","port":15014},{"name":"prometheus","port":42422}],"selector":{"istio":"mixer","istio-mixer-type":"telemetry"}}}
    creationTimestamp: "2021-02-17T17:01:27Z"
    labels:
      app: mixer
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: mixer
      istio.io/rev: default
      operator.istio.io/component: Telemetry
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.7.3
      release: istio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":9091,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15004,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15014,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":42422,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:istio: {}
            f:istio-mixer-type: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: istioctl
      operation: Update
      time: "2021-02-17T17:01:27Z"
    name: istio-telemetry
    namespace: istio-system
    resourceVersion: "3421346"
    selfLink: /api/v1/namespaces/istio-system/services/istio-telemetry
    uid: 4d2dd4c2-3e48-4c46-b09e-6ae19b3cc79f
  spec:
    clusterIP: 10.100.200.205
    ports:
    - name: grpc-mixer
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: grpc-mixer-mtls
      port: 15004
      protocol: TCP
      targetPort: 15004
    - name: http-monitoring
      port: 15014
      protocol: TCP
      targetPort: 15014
    - name: prometheus
      port: 42422
      protocol: TCP
      targetPort: 42422
    selector:
      istio: mixer
      istio-mixer-type: telemetry
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istiocoredns","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"AddonComponents","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.3","release":"istio"},"name":"istiocoredns","namespace":"istio-system"},"spec":{"ports":[{"name":"dns","port":53,"protocol":"UDP"},{"name":"dns-tcp","port":53,"protocol":"TCP"}],"selector":{"app":"istiocoredns"}}}
    creationTimestamp: "2021-02-17T17:01:26Z"
    labels:
      app: istiocoredns
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: default
      operator.istio.io/component: AddonComponents
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.7.3
      release: istio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":53,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":53,"protocol":"UDP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: istioctl
      operation: Update
      time: "2021-02-17T17:01:26Z"
    name: istiocoredns
    namespace: istio-system
    resourceVersion: "3421277"
    selfLink: /api/v1/namespaces/istio-system/services/istiocoredns
    uid: 29747494-e26d-4721-8928-e72ac413ef90
  spec:
    clusterIP: 10.100.200.91
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    selector:
      app: istiocoredns
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"pilot","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.3","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"ports":[{"name":"grpc-xds","port":15010},{"name":"https-dns","port":15012},{"name":"https-webhook","port":443,"targetPort":15017},{"name":"http-monitoring","port":15014},{"name":"dns-tls","port":853,"protocol":"TCP","targetPort":15053}],"selector":{"app":"istiod","istio":"pilot"}}}
    creationTimestamp: "2021-02-17T17:00:27Z"
    labels:
      app: istiod
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.7.3
      release: istio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":853,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15010,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15012,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15014,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
            f:istio: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: istioctl
      operation: Update
      time: "2021-02-17T17:00:27Z"
    name: istiod
    namespace: istio-system
    resourceVersion: "3420944"
    selfLink: /api/v1/namespaces/istio-system/services/istiod
    uid: 85404b32-2f3c-4ef1-9d1e-15320fe0abcb
  spec:
    clusterIP: 10.100.200.59
    ports:
    - name: grpc-xds
      port: 15010
      protocol: TCP
      targetPort: 15010
    - name: https-dns
      port: 15012
      protocol: TCP
      targetPort: 15012
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: 15017
    - name: http-monitoring
      port: 15014
      protocol: TCP
      targetPort: 15014
    - name: dns-tls
      port: 853
      protocol: TCP
      targetPort: 15053
    selector:
      app: istiod
      istio: pilot
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
